// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves a secret value to the OS keychain.
 * 
 * The `key` must be one of the allowed secret identifiers.
 */
async saveSecret(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_secret", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads a secret from the OS keychain.
 * 
 * Returns `Ok(None)` when the secret has not been set.
 * The `key` must be one of the allowed secret identifiers.
 */
async getSecret(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_secret", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a secret from the OS keychain.
 * 
 * Missing entries are treated as success (idempotent delete).
 * The `key` must be one of the allowed secret identifiers.
 */
async deleteSecret(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_secret", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tests Websupport API credentials via `GET /v2/check`.
 * 
 * Returns `true` when the API reports `{ "verified": true }`.
 */
async websupportTestConnection() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_test_connection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches DNS zone metadata for `domain` via `GET /v2/service/{domain}/dns/zone`.
 */
async websupportGetDnsZone(domain: string) : Promise<Result<DnsZone, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_get_dns_zone", { domain }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists all DNS records for `domain`, paging through the collection.
 */
async websupportListDnsRecords(domain: string) : Promise<Result<DnsRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_list_dns_records", { domain }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a DNS record via `POST /v2/service/{domain}/dns/record` (204 on success).
 */
async websupportCreateDnsRecord(domain: string, record: CreateDnsRecordInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_create_dns_record", { domain, record }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates a DNS record via `PUT /v2/service/{domain}/dns/record/{recordId}` (204 on success).
 */
async websupportUpdateDnsRecord(domain: string, recordId: string, record: CreateDnsRecordInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_update_dns_record", { domain, recordId, record }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a DNS record via `DELETE /v2/service/{domain}/dns/record/{recordId}` (204 on success).
 */
async websupportDeleteDnsRecord(domain: string, recordId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_delete_dns_record", { domain, recordId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists hostings for the authenticated user (`GET /v1/user/{id}/hosting`).
 */
async websupportListHostings() : Promise<Result<Hosting[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_list_hostings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists domains (vhosts) under a hosting
 * (`GET /v1/user/{id}/hosting/{hostingId}/vhost`).
 */
async websupportListDomains(hostingId: string) : Promise<Result<VHost[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_list_domains", { hostingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists mailboxes under a hosting
 * (`GET /v1/user/{id}/hosting/{hostingId}/mailbox`).
 */
async websupportListMailboxes(hostingId: string) : Promise<Result<Mailbox[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_list_mailboxes", { hostingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a mailbox
 * (`POST /v1/user/{id}/hosting/{hostingId}/domain/{domainId}/mailbox`).
 * 
 * Password is never written to logs.
 */
async websupportCreateMailbox(hostingId: string, domainId: string, input: CreateMailboxInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_create_mailbox", { hostingId, domainId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates a mailbox via POST (not PUT)
 * (`POST /v1/user/{id}/hosting/{hostingId}/domain/{domainId}/mailbox/{mailboxId}`).
 * 
 * Password is never written to logs.
 */
async websupportUpdateMailbox(hostingId: string, domainId: string, mailboxId: string, input: UpdateMailboxInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_update_mailbox", { hostingId, domainId, mailboxId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a mailbox
 * (`DELETE /v1/user/{id}/hosting/{hostingId}/domain/{domainId}/mailbox/{mailboxId}`).
 */
async websupportDeleteMailbox(hostingId: string, domainId: string, mailboxId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("websupport_delete_mailbox", { hostingId, domainId, mailboxId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
/**
 * Input for creating or updating a DNS record.
 */
export type CreateDnsRecordInput = { 
/**
 * Record type: A, AAAA, ANAME, CAA, CNAME, DNSSEC, MX, NS, SRV, TXT, CERT, LOC, SSHFP, TLSA, DS.
 */
type: string; name: string; content?: string | null; ttl: number; priority?: number | null; port?: number | null; weight?: number | null }
/**
 * Input for creating a mailbox. Password is never logged.
 * 
 * `Debug` is implemented by hand to redact `password` — this is the
 * safety net for any future `{:?}` of the whole struct (panic messages,
 * a stray debug log, etc.), on top of the explicit field-level logging
 * already used in `websupport_create_mailbox`.
 */
export type CreateMailboxInput = { email: string; password: string; ipCheck?: boolean | null; ips?: string[] | null; countryCheck?: boolean | null; countries?: string[] | null; imapDisabled?: boolean | null; pop3Disabled?: boolean | null; note?: string | null }
/**
 * A DNS record returned by the Websupport API.
 * 
 * Numeric fields use `i32` (fits DNS TTL/priority/port/weight and TS `number`).
 */
export type DnsRecord = { 
/**
 * Record id (null for some synthetic entries).
 */
id: number | null; name: string; content: string; ttl: number; priority: number | null; port: number | null; weight: number | null; 
/**
 * Record type: A, AAAA, ANAME, CAA, CNAME, DNSSEC, MX, NS, SRV, TXT, …
 */
type: string }
/**
 * DNS zone metadata for a domain.
 */
export type DnsZone = { name: string; lastCheck: string | null; dnssecSigning: string | null }
/**
 * A hosting product under the authenticated user.
 */
export type Hosting = { id: number; name: string; uuid?: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * A mailbox under a hosting.
 */
export type Mailbox = { id: number; 
/**
 * Full email address or local part (API-dependent).
 */
email?: string | null; domain?: string | null; note?: string | null; ipCheck?: boolean | null; countryCheck?: boolean | null; imapDisabled?: boolean | null; pop3Disabled?: boolean | null }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * Input for updating a mailbox (POST, not PUT). Password is never logged.
 * 
 * `Debug` is implemented by hand to redact `password` (see
 * `CreateMailboxInput`'s impl for the rationale).
 */
export type UpdateMailboxInput = { password?: string | null; ipCheck?: boolean | null; ips?: string[] | null; countryCheck?: boolean | null; countries?: string[] | null; imapDisabled?: boolean | null; pop3Disabled?: boolean | null; note?: string | null }
/**
 * A virtual host (domain) under a hosting.
 */
export type VHost = { id: number; 
/**
 * Domain name (API may expose as `name` or `domain`).
 */
name: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
