use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        notifications, preferences, quick_pane, recovery, secrets, websupport_dns, websupport_v1,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        secrets::save_secret,
        secrets::get_secret,
        secrets::delete_secret,
        websupport_dns::websupport_test_connection,
        websupport_dns::websupport_get_dns_zone,
        websupport_dns::websupport_list_dns_records,
        websupport_dns::websupport_create_dns_record,
        websupport_dns::websupport_update_dns_record,
        websupport_dns::websupport_delete_dns_record,
        websupport_v1::websupport_list_hostings,
        websupport_v1::websupport_list_domains,
        websupport_v1::websupport_list_mailboxes,
        websupport_v1::websupport_create_mailbox,
        websupport_v1::websupport_update_mailbox,
        websupport_v1::websupport_delete_mailbox,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
